#include "game.h"

extern tsgl_print_settings printsettings_overlay;
extern tsgl_print_settings printsettings_subgames;
extern tsgl_print_settings printsettings_subgames_line;
extern tsgl_print_settings printsettings_subgames_line_stroke;
extern tsgl_print_settings printsettings_gametitle;
extern tsgl_print_settings printsettings_message;
